baseURL = 'https://gurucodes.dev/'
languageCode = 'en-us'
title = 'GuruCodes'
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params]
mainSections = ["lessons", "snippets"]

[params.algolia]
vars = ["title", "description", "summary", "date", "publishdate", "lastmod", "permalink"]
params = ["tags"]

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4